package com.dz.logparser;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * The main Spring Boot application. Generated by Spring Boot Initializr
 */
@SpringBootApplication
public class LogparserApplication {

	public static void main(String[] args) {
		SpringApplication.run(LogparserApplication.class, args);
	}

}
